### ISSUE TITLE
Error in a$kbet$summary : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by pengcui** [bzhanglab/OmicsEV#1]
[RNA_seq_1_datasets.zip](https://github.com/bzhanglab/OmicsEV/files/4203411/RNA_seq_1_datasets.zip)

I'm a user of OmicsEV for a proteome dataset and I found a potential fatal bug of OmicsEV. My proteome dataset has 215 samples and total 22 batches. However when I ran it in OmicsEV, the R printed error with "Error in a$kbet$summary : $ operator is invalid for atomic vectors". 

After several days trial and error, I find the problem is the batch number. When there are many batches, OmicsEV will print the same error. But when I set my proteome data into several batches, OmicsEV works well.

Except my own dataset, I also experimented the example RNA-Seq data provided by OmicsEV itself. And when I set it with more batches (in the attachment), the example data also print the same error.

This maybe a potential fatal bug of OmicsEV and I don't know how to deal with it. I also put the modified RNA-Seq example dataset in the attachment and you could find out what is the real problem. Thanks!

**Comment by wenbostar** [comment]
When the number of samples in a batch is very small, you may get this error. I just removed the kbet function from OmicsEV.
