### ISSUE TITLE
Phosphoproteomics data

### ISSUE THREAD

**Issue by CuckooWang** [bzhanglab/OmicsEV#4]
I tried to run OmicsEV with phosphorylaiton data in format as below:
![image](https://user-images.githubusercontent.com/50347905/192326158-f71a9e39-487f-4e28-8fe1-ab91634e5a19.png)
And I used code as:
![image](https://user-images.githubusercontent.com/50347905/192326418-9da78c28-df09-48cb-8df9-e10b94c7b888.png)
Then I got a error message say "Mon Sep 26 15:16:04 2022: complex analysis ...
Error in import_network_data(type = data_type, species = species) : 
  object 'x' not found"

**Comment by CuckooWang** [comment]
![image](https://user-images.githubusercontent.com/50347905/192327620-a53949ab-e6e5-44d3-b9de-6dfc45c00f44.png)

**Comment by wenbostar** [comment]
Phospho data so far is not well supported by OmicsEV. For now, you can set the parameter species="NO". This will disable the protein complex-based analysis which caused the erorr you saw.
