### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by toddcreasy** [bzhanglab/OmicsEV#6]
Hi,

Can I ask a favor and have someone create the Dockerfile used to create this container and commit to the repository? I'm doing some work with OmicsEV and this would be a big help.

Thanks!

-todd

**Comment by wenbostar** [comment]
Is this what you want? https://github.com/bzhanglab/OmicsEV/blob/docker/Dockerfile

**Comment by toddcreasy** [comment]
That's perfect! Thanks!
